name: Publish Release to GHCR

on:
  workflow_run:
    workflows: ["Auto Bump and Release"]
    types: [completed]

permissions:
  contents: read
  packages: write

jobs:
  publish-to-ghcr:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get latest release tag
        id: latest
        uses: actions/github-script@v7
        with:
          script: |
            const latest = await github.rest.repos.getLatestRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
            });
            core.setOutput('tag', latest.data.tag_name);

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          target: production
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.latest.outputs.tag }}
            ghcr.io/${{ github.repository }}:latest
          build-args: |
            VERSION=${{ steps.latest.outputs.tag }}
            APP_UID=1000
            APP_GID=1000
            LOG_DIR=logs
          cache-from: type=gha
          cache-to: type=gha,mode=max
